A method reversing string lines sequence implemented
SzymonB7/JavaIntro_Zadania pull request #31
Opened 2022-01-10 20:50 UTC by SzymonB7

2022-01-10 21:03 UTC, MateuszMarczak requested changes
jak w data.txt umieściełm "Kurs Java Lekcja 6 Pliki Wyjątki Pliki Koniec pliku" pisane bez nowej lini to niestety nie zadziałało, wypisało się w tej samej kolejności :). Dodatkowo "koniec pliku" wypisuje się jako "koniec pliku" a nie "pliku koniec" :D Zobacz może taką metodę ze Stringa "split" a następnie można wypisać od końca tabeli ;)

2022-01-10 21:19 UTC, SzymonB7 commented
No nie, teraz to jestem rozczarowany. Ja tu wprowadzam nowatorskie rozwiązanie, które sam wymyśliłem, które jest dopasowane do pliku, na którym trzeba było to przeprowadzić, w którym są słowa od nowych linii, tak żeby dla tego pliku i jego treści rezultat miał jakiś sens, a nie wyświetlał "pliku Koniec", a Ty mnie tu do jakichś gotowców odsyłasz, ech...

2022-01-10 22:15 UTC, MateuszMarczak commented
ale jak najbardziej doceniam nowatorskie rozwiązanie dopasowane do jednego pliku ;)

2022-01-10 23:17 UTC, SzymonB7 commented
Noo, dokładnie tego, który jest w zadaniu, a nie takiego ze Stringiem w jednej linii, którego nie ma w zadaniu ;)

2022-01-10 23:47 UTC, SzymonB7 commented
Poza tym dopasowane jest do każdego pliku, w którym jest String z wyrażeniami od nowej linii... czyli takiego jaki był w zadaniu :( Treść tego pliku jest specyficzna, wyrażenia w poszczególnych liniach mają sens i w tym rozwiązaniu wyświetlają się na konsoli w odwrotnej kolejności. Jeżeli chodzi o odwrotną kolejność słów można to było dookreślić, równie dobrze mogłaby to być odwrotna kolejność znaków,

2022-01-11 07:04 UTC, MateuszMarczak commented
Odwrotna kolejność wyrazów jest łatwiejsza do implementacji przy jednej linii niż zachowanie znaczenia dwóch wyrazów (przypadek "pliku Koniec"). 
I w sumie masz rację, powinno wyświetlać odwrotną kolejność znaków dla całego pliku (tutaj pamiętaj, że String jest po prostu tablicą char :)), co będzie jeszcze prostsze do implementacji :)

2022-01-11 16:20 UTC, SzymonB7 commented
No dobra, to było w sumie pierwsze co zrobiłem przy tym zadaniu, zanim nie stwierdziłem, że to pewnie nie o to chodzi.

2022-01-11 16:25 UTC, MateuszMarczak commented
no i teraz jest git :)

2022-01-11 16:25 UTC, MateuszMarczak approved these changes

2022-01-12 18:57 UTC, merged